### ISSUE TITLE
Tabbed layout

### ISSUE THREAD

**Issue by mhzrerfani** [mpourismaiel/dotfiles#3]
After we open terminals and change layout to tabbed when we change layout again there are some problems with each layout mode. 
- On Other layouts we don't have access to other tabs of tabbed terminal
- when switching to floating, tabbed terminal can't change position and fill empty space.
![image](https://github.com/mpourismaiel/dotfiles/assets/51866154/cbe994a6-a6b6-42c3-a638-893fd21c7776)

Suggestion features: 
- On full screen layout other terminals have opacity of 0
- Tabs size get smalller based of amount of tabs in tabbed terminal to have better access

**Comment by mpourismaiel** [comment]
Some stuff has been fixed. Specifically:

- Switching from tabbed layout to other layouts doesn't leave clients transparent. They turn opaque as soon as layout is changed out of tabbed.
- Tab bar should not appear in other screens and other tags.
- Tab bar is hidden when layout is changed out of tabbed.
- Active tab doesn't reset when switching between master/slave sections.

Will close the issue. Create a new one if there are any other issues you find. Thanks for debugging the layout. I appreciate it.
