### ISSUE TITLE
Telegram media viewer

### ISSUE THREAD

**Issue by mhzrerfani** [mpourismaiel/dotfiles#5]
![image](https://github.com/mpourismaiel/dotfiles/assets/51866154/067eb8ec-cfc1-4d73-9c73-eddf0d4e408b)
When we open media in telegram an app will be opened called media viewer that contains close button itself.
There's no need for top bar.

**Comment by mpourismaiel** [comment]
Should be fixed now, please reopen and mention me if there is a problem
